global:
  scrape_interval: 10s
  evaluation_interval: 1m

  external_labels:
    monitor: 'haru-order-service'


scrape_configs:
  - job_name: 'order-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8081']