spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/harudb-order?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: 123qwe
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8081

external:
  server:
    base-url: http://localhost:8080/
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      auto-offset-reset: earliest

management:
  endpoints:
    prometheus:
      enabled: true
    web:
      exposure:
        include: prometheus